### ISSUE TITLE
Merge 'randomize_tweets' reverted my commits

### ISSUE THREAD

**Issue by johnbuluba** [ModusVivendi/twitter-contest#10]
I am not sure what happened here, but it undid what i commited today.

Also i can modify the main scheduler so we dont have 2 schedulers. ;-)
Please contact me at buluba89 at gmail.com to talk about some issues!

Thanks!

**Comment by johnbuluba** [comment]
Checkout my fork for updated scheduler to handle random delays.

I know it is not the same, it doesnt randomize the posts throughout the day, rather randomizes the delay. But randomizing throughout the day is 'dangerous' because it may schedule all posts at the same time. Pretty unlikely yes, but its a possibility

**Comment by AuxProc** [comment]
The overwrite was accidental, but when I looked back at your changes on UpdateQueue, I'm not really convinced that they would have logically done what we needed.  I'm also partial to keeping the ability to easily schedule times of day that posts are not made, while limiting based on a total number of daily posts.  I've now redone the scheduler to use just apscheduler, which allows easier access to more advanced scheduling functions, without having to define as much custom scheduling actions within the main script.

**Comment by johnbuluba** [comment]
Its ok mate, i will continue to develop my own copy.
Have a nice one and continue the good work!
