### ISSUE TITLE
Errors when running? 

### ISSUE THREAD

**Issue by Seroria** [ModusVivendi/twitter-contest#17]
Hi,
Sorry if I'm really bad at this as I only just started learning python. I've tried launching your app in both 2.7 and 3.5 versions and both come to different errors, [here](https://gyazo.com/32c182d04528e73df793d6956c16452e) is a screenshot of me running in both python modules, hope you can help me troubleshoot this and again, apologies for being dumb and new. 

I understand that you say to run it in v3 of python but I couldn't figure out why pip3 installer wasn't working to install twitterAPI and that seems to clearly be the problem. It'd be great if you could help me figure this out, especially as it seems as simple as installing TwitterAPI for v3 of python.

Thanks,
Lucas

**Comment by AuxProc** [comment]
What is the error when trying to install TwitterAPI?

**Comment by Seroria** [comment]
My CMD says pip3 and python3 are not recognised commands which completely prevents me from installing it, which leads me to believe it's a problem with pip.

**Comment by Seroria** [comment]
A screenshot of me trying some of those commands is [here](https://gyazo.com/b1708ec91503c75194aebe5d9ef13385) and next to it showing the pip.exe's in my /Python27 Directory (I have run get-pip.py)

**Comment by Seroria** [comment]
@ModusVivendi sorry, forgot to tag you above
