### ISSUE TITLE
New scheduler does not seem to clear the queue properly

### ISSUE THREAD

**Issue by AuxProc** [ModusVivendi/twitter-contest#5]
After running the script with the newest scheduler yesterday afternoon and all night, I noticed it did not once clear the queue and the script eventually crashed.  I think the new scheduler has caused some instabilities I cant identify.

**Comment by johnbuluba** [comment]
Because  its single threaded now if something in the functions that it calls crash the whole script will crash. I will make it creates threads again in a while

**Comment by johnbuluba** [comment]
Did it throw any exceptions or it just stuck ?

There are  2 possibilities i think.  Either something raised an exception and crashed the whole thing or some call to the api blocked everything

Either way both situation are fixed now and i look it more carefully later when i have time

**Comment by buluba89** [comment]
A wait
